// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOD5wNNiJpmo9RuIp_2PTcuPcEgtsxetA',
    appId: '1:73669677305:web:6e1130bf485a5ec7ad9228',
    messagingSenderId: '73669677305',
    projectId: 'forall-c5061',
    authDomain: 'forall-c5061.firebaseapp.com',
    storageBucket: 'forall-c5061.firebasestorage.app',
    measurementId: 'G-285F7B5VTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_bDUu84gxH5BgZxeUj_G3Eo-k7SJYWk',
    appId: '1:73669677305:android:e370c7b8b6a17a4bad9228',
    messagingSenderId: '73669677305',
    projectId: 'forall-c5061',
    storageBucket: 'forall-c5061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLORci5U9NinfUbLoAvHp5UqbB09SkRc',
    appId: '1:73669677305:ios:61abaf4a3f911110ad9228',
    messagingSenderId: '73669677305',
    projectId: 'forall-c5061',
    storageBucket: 'forall-c5061.firebasestorage.app',
    iosClientId: '73669677305-jej454455c5auvqr0r2l564dasuapm3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.authcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYLORci5U9NinfUbLoAvHp5UqbB09SkRc',
    appId: '1:73669677305:ios:61abaf4a3f911110ad9228',
    messagingSenderId: '73669677305',
    projectId: 'forall-c5061',
    storageBucket: 'forall-c5061.firebasestorage.app',
    iosClientId: '73669677305-jej454455c5auvqr0r2l564dasuapm3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.authcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOD5wNNiJpmo9RuIp_2PTcuPcEgtsxetA',
    appId: '1:73669677305:web:e525fa402ef8ee48ad9228',
    messagingSenderId: '73669677305',
    projectId: 'forall-c5061',
    authDomain: 'forall-c5061.firebaseapp.com',
    storageBucket: 'forall-c5061.firebasestorage.app',
    measurementId: 'G-HJJD2QFNLY',
  );
}
